In [2]:
import numpy as np
str=np.array(["2.3","23.3","234.45"])
print(str)


['2.3' '23.3' '234.45']


In [14]:

import numpy as np
a=np.array([10,20,23,34,45])
print(a)
print(a.ndim)

[10 20 23 34 45]
1


In [8]:
# 2-d array
import numpy as np
a=np.array([[10,20],[23,34],[30,45]])
print(a)
print(a.ndim)

[[10 20]
 [23 34]
 [30 45]]
2


In [10]:
import numpy as np
a=np.array([[[10,20],[23,34],[30,45]]])
print(a)
print(a.ndim)

[[[10 20]
  [23 34]
  [30 45]]]
3


In [11]:
import numpy as np
a=np.array([[[[10,20],[23,34],[30,45]]]])
print(a)
print(a.ndim)

[[[[10 20]
   [23 34]
   [30 45]]]]
4


In [2]:
import numpy as np
a=np.array([[[[[10,22,23,20]] , [[22,33,23,34]], [[21,89,30,45]]]]])
print(a)
print(a.ndim)
print(a.shape)

[[[[[10 22 23 20]]

   [[22 33 23 34]]

   [[21 89 30 45]]]]]
5
(1, 1, 3, 1, 4)


In [ ]:
import numpy as np
a=np.array([[[[[10,20],[23,34],[30,45]]]]])
print(a)
print(a.ndim)

In [1]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a.size)


4


In [3]:
import numpy as np
a=np.array(([[[[[13,23,33,22,],[23,233,32,4],[21,3,302,14]]]]]))
print("array=",a)
print("size=",a.size)
print("dimension=",a.ndim)
print("shape=",a.shape)
print("data type=",a.dtype)


array= [[[[[ 13  23  33  22]
    [ 23 233  32   4]
    [ 21   3 302  14]]]]]
size= 12
dimension= 5
shape= (1, 1, 1, 3, 4)
data type= int32


In [4]:
import numpy as ap 
a=ap.array(([[[[[13,23,33,22,],[23,233,32,4],[21,3,302,14]]]]]))
print("array=",a)
print("size=",a.size)
print("dimension=",a.ndim)
print("shape=",a.shape)
print("data type=",a.dtype)
 

array= [[[[[ 13  23  33  22]
    [ 23 233  32   4]
    [ 21   3 302  14]]]]]
size= 12
dimension= 5
shape= (1, 1, 1, 3, 4)
data type= int32


In [5]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
import numpy as np
a=np.eye(5)
 
print(a)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
import numpy as np
a=np.array([1,22,12,15,4,26,11,10,34,5,6,8,8,9,0])
b=a.reshape(3,5)
print(b)

[[ 1 22 12 15  4]
 [26 11 10 34  5]
 [ 6  8  8  9  0]]


In [9]:
a=np.array([[1,2],[3,4]])
print(a.flatten())

[1 2 3 4]


In [10]:
import pandas as pd

df = pd.read_csv("students.csv")

print(df)


    Name  English  Maths  Science  Computer  Hindi  Total
0  Rahul       78     85       90        88     80    421
1   Riya       92     89       95        91     87    454
2   Aman       67     74       70        76     72    359
3  Priya       88     90       86        94     89    447
4  Karan       75     80       78        82     77    392
5  Sneha       91     93       89        95     90    458
6  Ankit       69     71       68        73     70    351
7   Neha       84     86       88        90     85    433
8  Vikas       73     76       79        81     74    383
9  Pooja       95     97       94        98     96    480
