In [2]:
import numpy as np

b = np.array(([[10,11],[22,33]], [[20,21],[30,31]]))
print(b[0,1,0])

22


In [5]:
import numpy as np

b = np.array(([[10,11],[22,33]],[[20,21],[30,31]]))
print(b)
print(b[0,1,1])

[[[10 11]
  [22 33]]

 [[20 21]
  [30 31]]]
33


In [6]:
a=np.array(([22,23,24]))
b=np.array(([20,21,23]))
print(a+b)

[42 44 47]


In [7]:
a=np.array(([22,23,24]))
b=np.array(([20,21,23]))
print(a-b)

[2 2 1]


In [8]:
a=np.array(([2,3,4]))
b=np.array(([2,1,3]))
print(a*b)

[ 4  3 12]


In [9]:
a=np.array(([2,3,4]))
b=np.array(([2,1,3]))
print(a/b)

[1.         3.         1.33333333]


In [11]:
a=np.array(([2,3,4]))
print(a**2)

[ 4  9 16]


In [12]:
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [33]:
a=np.zeros([4,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
a=np.ones([3,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
a=[2,43,4,56,43,12]
a.sort()
print(a[-1])
print(a[0])

56
2


In [26]:
a=np.array([2,43,4,56,43,12])
print("mean=",np.mean(a))


mean= 26.666666666666668


In [27]:
a=np.array([2,43,4,56,43,12])
print("median=",np.median(a))


median= 27.5


In [31]:
a=np.array([2,43,4,56,43,12])

print(np.sort(a)[::-1])


[56 43 43 12  4  2]


In [32]:
a=np.array([2,43,4,56,43,12])
result=a[a>5]
print(result)

[43 56 43 12]


In [2]:
class stdent:
    def __init__(self,name,age):
        self.name=name
        self.age=age

    def display(self):
         print("name=",self.name)
         print("age=",self.age)

s1=stdent("rahul",20)
s2=stdent("riya",30)
s1.display()
s2.display()

name= rahul
age= 20
name= riya
age= 30


In [6]:
class student:
    def __init__(self,name,age):
        self.name=name
        self.age=age
    def display(self):
        print("name=",self.name)
        print("age=",self.age)
s1=student("rahul",20)
s2=student("riya",22)
s1.display()
s2.display()


    

name= rahul
age= 20
name= riya
age= 22


In [18]:
a=np.array([-2,-43,-4,56,-43,12])
print("absolute    =",np.abs(a))
print("sqrt    =",np.sqrt(a))
print("exponential     =",np.exp(a))
print("logarathimic     =",np.log(a))
print("sin    =",np.sin(a))
print("cos    =",np.cos(a))
print("tan    =",np.tan(a))




absolute    = [ 2 43  4 56 43 12]
sqrt    = [       nan        nan        nan 7.48331477        nan 3.46410162]
exponential     = [1.35335283e-01 2.11513104e-19 1.83156389e-02 2.09165950e+24
 2.11513104e-19 1.62754791e+05]
logarathimic     = [       nan        nan        nan 4.02535169        nan 2.48490665]
sin    = [-0.90929743  0.83177474  0.7568025  -0.521551    0.83177474 -0.53657292]
cos    = [-0.41614684  0.5551133  -0.65364362  0.85322011  0.5551133   0.84385396]
tan    = [ 2.18503986  1.49838734 -1.15782128 -0.61127369  1.49838734 -0.63585993]


In [21]:
a=np.array([2,43,4,56,43,12])
b=a.copy()
b[0]=101
print(b)

[101  43   4  56  43  12]


In [23]:
a=np.array([2,43,4,56,43,12])
b=a.view()
print(b)

[ 2 43  4 56 43 12]


In [30]:
print(np.random.randint(6))
print(np.random.rand(6))
print(np.random.randint(1,10,2))
print(np.random.randint(1,100,(3,4)))

5
[0.86799347 0.17144559 0.52355666 0.65944209 0.48476873 0.25381941]
[1 2]
[[14 15 26 12]
 [93 81 75  8]
 [49 42 82 29]]


In [31]:
a=np.array([2,43,4,56,43,12])
print(a+10)

[12 53 14 66 53 22]


In [36]:
a=np.array(([[2,3],[2,4]]))
print(a.ndim)
print(a*5)

2
[[10 15]
 [10 20]]


In [45]:
a=np.array([12,53,14,66,53,22])
print("mean=",a.mean())
print("max=",a.max())
print("min=",a.min())

mean= 36.666666666666664
max= 66
min= 12


In [7]:
import numpy as np
salary=np.linspace(10000,25000,90)
print("salary=",salary)
print("salary after incerement=",salary*1.5)
print("min slary=",np.min(salary))
print("max salry=",np.max(salary))
print("median=",np.median(salary))

 


salary= [10000.         10168.53932584 10337.07865169 10505.61797753
 10674.15730337 10842.69662921 11011.23595506 11179.7752809
 11348.31460674 11516.85393258 11685.39325843 11853.93258427
 12022.47191011 12191.01123596 12359.5505618  12528.08988764
 12696.62921348 12865.16853933 13033.70786517 13202.24719101
 13370.78651685 13539.3258427  13707.86516854 13876.40449438
 14044.94382022 14213.48314607 14382.02247191 14550.56179775
 14719.1011236  14887.64044944 15056.17977528 15224.71910112
 15393.25842697 15561.79775281 15730.33707865 15898.87640449
 16067.41573034 16235.95505618 16404.49438202 16573.03370787
 16741.57303371 16910.11235955 17078.65168539 17247.19101124
 17415.73033708 17584.26966292 17752.80898876 17921.34831461
 18089.88764045 18258.42696629 18426.96629213 18595.50561798
 18764.04494382 18932.58426966 19101.12359551 19269.66292135
 19438.20224719 19606.74157303 19775.28089888 19943.82022472
 20112.35955056 20280.8988764  20449.43820225 20617.97752809
 20786.51685393 2

In [6]:
import os

print(os.listdir())

['Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Untitled5.ipynb', 'Untitled6.ipynb', 'name.txt', 'newname.txt', 'sqlite.ipynb', 'cpp-tiny-ray-tracer.ipynb', 'Intro.ipynb', 'Lorenz.ipynb', 'cpp.ipynb', 'r.ipynb', 'cpp-third-party-libs.ipynb']


In [2]:
import pandas as pd
df = pd.read_csv("students.csv")
print(df)
df.shape
print(df.describe())

    Name  English  Maths  Science  Computer  Hindi  Total
0  Rahul       78     85       90        88     80    421
1   Riya       92     89       95        91     87    454
2   Aman       67     74       70        76     72    359
3  Priya       88     90       86        94     89    447
4  Karan       75     80       78        82     77    392
5  Sneha       91     93       89        95     90    458
6  Ankit       69     71       68        73     70    351
7   Neha       84     86       88        90     85    433
8  Vikas       73     76       79        81     74    383
9  Pooja       95     97       94        98     96    480
         English      Maths    Science   Computer     Hindi       Total
count  10.000000  10.000000  10.000000  10.000000  10.00000   10.000000
mean   81.200000  84.100000  83.700000  86.800000  82.00000  417.800000
std    10.130263   8.595218   9.510813   8.416914   8.69227   44.329072
min    67.000000  71.000000  68.000000  73.000000  70.00000  351.000000
25

In [3]:
import pandas as pd
marks=pd.Series([34,33,45,32],index=["Ananya","Amit","Chetna","Dev"])
print(marks)

Ananya    34
Amit      33
Chetna    45
Dev       32
dtype: int64


In [ ]:
    Name  English  Maths  Science  Computer  Hindi  Total
0  Rahul       78     85       90        88     80    421
1   Riya       92     89       95        91     87    454
2   Aman       67     74       70        76     72    359
3  Priya       88     90       86        94     89    447
4  Karan       75     80       78        82     77    392
5  Sneha       91     93       89        95     90    458
6  Ankit       69     71       68        73     70      351
7   Neha       84     86       88        90     85    433
8  Vikas       73     76       79        81     74    383
9  Pooja       95     97       94        98     96    480