In [10]:
import numpy as np
a=np.array(([1,2,3],[4,5,6]))
print(a)

[[1 2 3]
 [4 5 6]]


In [15]:
import numpy as np
a=np.array(([1,2,3,4],[5,6,7,8],[9,0,1,2],[3,4,5,6]))
print(a)
print(a.ndim)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]
 [3 4 5 6]]
2


In [16]:
import numpy as np
a=np.array(([[1,2,3,4],[5,6,7,8]],[[9,0,1,2],[3,4,5,6]]))
print(a)
print(a.ndim)

[[[1 2 3 4]
  [5 6 7 8]]

 [[9 0 1 2]
  [3 4 5 6]]]
3


In [23]:
a=np.array(([[[[1,2,3,4]]]],[[[[5,6,7,8]]]],[[[[9,0,1,2]]]],[[[[3,4,5,6]]]]))
print(a)
print(a.ndim)

[[[[[1 2 3 4]]]]



 [[[[5 6 7 8]]]]



 [[[[9 0 1 2]]]]



 [[[[3 4 5 6]]]]]
5


In [25]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [4]:
import numpy as np
a=np.array(([10,20,30,40,50]))
print(a[1:4])

[20 30 40]


In [5]:
a=np.array(([10,20,30,40,50]))
b=np.array([1,2,3,4,5])
print(a+b)

[11 22 33 44 55]


In [6]:
a=np.array(([10,20,30,40,50]))
b=np.array([1,2,3,4,5])
print(a*b)

[ 10  40  90 160 250]


In [8]:
a=np.array(([1,4,9,16,25]))
print(np.sqrt(a))

[1. 2. 3. 4. 5.]


In [4]:
import numpy as np


a = np.ones((4, 4, 4, 4))

print("Shape of the array:")
print(a.shape)

print("\nNumber of dimensions:")
print(a.ndim)


Shape of the array:
(4, 4, 4, 4)

Number of dimensions:
4


In [3]:

import numpy as np
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
a=np.zeros([4,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
a=np.array(([[10,20],[30,40]],[[0,9],[9,8]]))
print(a[0,1,0])
print(a.ndim)

30
3


In [7]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
