In [25]:
import numpy as np
a=np.array([[[1,2],[2,1]],[[2,3],[3,2]]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.flatten())
print(a[0,1,0])

[[[1 2]
  [2 1]]

 [[2 3]
  [3 2]]]
3
(2, 2, 2)
8
int32
[1 2 2 1 2 3 3 2]
2


In [18]:
a=np.linspace(1,16,8)
print(a)

[ 1.          3.14285714  5.28571429  7.42857143  9.57142857 11.71428571
 13.85714286 16.        ]


In [22]:
a=np.arange(1,13)
print(a)
b=a.reshape(3,4)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
a=np.array([1,2,3,4,5,6,7,8,9,0])
print(a)
#THESE ARE ALL UNIVERSAL FUNCTIONS IN NUMPY
print(np.abs(a))
print(np.exp(a))
print(np.log(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[1 2 3 4 5 6 7 8 9 0]
[1 2 3 4 5 6 7 8 9 0]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 1.00000000e+00]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458       -inf]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849  0.        ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026  1.        ]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.        ]


In [39]:
a=np.array([1,2,3])
print(a.view())


[1 2 3]


In [42]:
print(np.random.rand(6))#float
print(np.random.randint(1,1000,5))#int
print(np.random.randint(1,100,(3,4)))
9

[0.7592581  0.68888931 0.32956301 0.4566872  0.73495986 0.28695766]
[167  96 873 307 905]
[[27  4 78 32]
 [28 49 43 35]
 [20 55 19 61]]


In [44]:
marks=np.array([34,24,76,98,48,83])
print(marks>50)
print(marks<50)

[False False  True  True False  True]
[ True  True False False  True False]


In [48]:
marks=np.array([34,24,76,98,48,83])
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))


      

60.5
98
24


In [58]:
salary=np.linspace(5000,10000,50)
print(salary)
print(np.max(salary))
print(np.min(salary))
print(np.mean(salary))
print("incerement= ",salary*1.5)

[ 5000.          5102.04081633  5204.08163265  5306.12244898
  5408.16326531  5510.20408163  5612.24489796  5714.28571429
  5816.32653061  5918.36734694  6020.40816327  6122.44897959
  6224.48979592  6326.53061224  6428.57142857  6530.6122449
  6632.65306122  6734.69387755  6836.73469388  6938.7755102
  7040.81632653  7142.85714286  7244.89795918  7346.93877551
  7448.97959184  7551.02040816  7653.06122449  7755.10204082
  7857.14285714  7959.18367347  8061.2244898   8163.26530612
  8265.30612245  8367.34693878  8469.3877551   8571.42857143
  8673.46938776  8775.51020408  8877.55102041  8979.59183673
  9081.63265306  9183.67346939  9285.71428571  9387.75510204
  9489.79591837  9591.83673469  9693.87755102  9795.91836735
  9897.95918367 10000.        ]
10000.0
5000.0
7500.0
incerement=  [ 7500.          7653.06122449  7806.12244898  7959.18367347
  8112.24489796  8265.30612245  8418.36734694  8571.42857143
  8724.48979592  8877.55102041  9030.6122449   9183.67346939
  9336.73469388  948

In [3]:
import pandas as pd
o=pd.read_csv("student.csv")
print(o)

      Student Name  English  Mathematics  Science  Social Studies  \
0     Aarav Sharma     85.0         92.0     88.0            79.0   
1      Ananya Iyer     78.0         85.0     80.0            82.0   
2      Arjun Verma     90.0         95.0     94.0            89.0   
3       Diya Patel     65.0         72.0     70.0            68.0   
4     Ishaan Reddy     82.0         78.0     85.0            90.0   
5       Kavya Nair     92.0         89.0     91.0            95.0   
6      Rohan Gupta     70.0         65.0     74.0            72.0   
7   Sanya Malhotra     88.0         91.0     87.0            84.0   
8     Vivaan Joshi     60.0         58.0     62.0            65.0   
9        Zara Khan     84.0         80.0     82.0            86.0   
10               s      NaN          NaN      NaN             NaN   

    Computer Science  Total Marks  
0               95.0        439.0  
1               88.0        413.0  
2               98.0        466.0  
3               75.0       

In [6]:
marks=pd.Series([80,90,75],index=["A","B","C"])
print(marks)


A    80
B    90
C    75
dtype: int64


In [8]:
import pandas as pd
data = {
    "Roll_No":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "Name": ["Amit", "Bina", "Chetan", "Dev", "Esha", "Ram", "Gita", "Hari", "Indu", "Jay", "Kiran", "Lata", "Manish", "Neha", "Om"],
    "Age":[5,6,7,8,6,7,8,4,6,7,8,6,7,5,7],
    "Marks": [85, 90, 78, 92, 88, 75, 82, 95, 89, 70, 84, 91, 79, 86, 93]
}
df = pd.DataFrame(data)
print(df)


    Roll_No    Name  Age  Marks
0         1    Amit    5     85
1         2    Bina    6     90
2         3  Chetan    7     78
3         4     Dev    8     92
4         5    Esha    6     88
5         6     Ram    7     75
6         7    Gita    8     82
7         8    Hari    4     95
8         9    Indu    6     89
9        10     Jay    7     70
10       11   Kiran    8     84
11       12    Lata    6     91
12       13  Manish    7     79
13       14    Neha    5     86
14       15      Om    7     93


In [33]:
import pandas as pd
data = {
    "ID":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],
    "Name": ["Amit", "Bina", "Chetan", "Dev", "Esha", "Ram", "Gita", "Hari", "Indu", "Jay", "Kiran","Shyam","Lata", "Manish", "Neha", "Om"],
    "department_no. ":[5,6,7,8,6,7,8,4,6,7,8,6,7,5,None,7],
    "Salary": [85, 90, 78, 92, 88, 75, 82, 95, 89, 70,None,84, 91, 79, 86,93]
}
df = pd.DataFrame(data)
#dept_5_total = df[df["department_no. "] == 7]["Salary"].mean()
p#rint("Total Salary for Department 5:", dept_5_total)
ts=df.groupby("department_no. ")[


Total Salary for Department 5: 81.4


In [14]:
f=pd.read_csv("student.csv")
print(f)


      Student Name  English  Mathematics  Science  Social Studies  \
0     Aarav Sharma     85.0         92.0     88.0            79.0   
1      Ananya Iyer     78.0         85.0     80.0            82.0   
2      Arjun Verma     90.0         95.0     94.0            89.0   
3       Diya Patel     65.0         72.0     70.0            68.0   
4     Ishaan Reddy     82.0         78.0     85.0            90.0   
5       Kavya Nair     92.0         89.0     91.0            95.0   
6      Rohan Gupta     70.0         65.0     74.0            72.0   
7   Sanya Malhotra     88.0         91.0     87.0            84.0   
8     Vivaan Joshi     60.0         58.0     62.0            65.0   
9        Zara Khan     84.0         80.0     82.0            86.0   
10               s      NaN          NaN      NaN             NaN   

    Computer Science  Total Marks  
0               95.0        439.0  
1               88.0        413.0  
2               98.0        466.0  
3               75.0       

In [17]:
f=pd.read_csv("r&c.csv")
print(f)
print(df.head(50))


   Col_1  Col_2  Col_3  Col_4  Col_5  Col_6  Col_7  Col_8  Col_9  Col_10  Col_11  Col_12  Col_13  Col_14  Col_15
0   0      42     87     15     93     55     24  ...                                                           
1   1      12     65     78     34     89     11  ...                                                           
2   2      99     31     44     72     10     85  ...                                                           
3   3      63     50     82     11     67     94  ...                                                           
4   4      27     94     36     58     81     73  ...                                                           
5   5      54     23     87     41     19     60  ...                                                           
6   6      81     76     12     90     33     45  ...                                                           
7   7      39     11     68     53     74     21  ...                                           

In [24]:
import pandas as pd
df = pd.read_csv("r&c.csv")
df.head(10)
print(df.info())
df.tail(5)
df.describe()



<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 1 columns):
 #   Column                                                                                                             Non-Null Count  Dtype
---  ------                                                                                                             --------------  -----
 0       Col_1  Col_2  Col_3  Col_4  Col_5  Col_6  Col_7  Col_8  Col_9  Col_10  Col_11  Col_12  Col_13  Col_14  Col_15  50 non-null     str  
dtypes: str(1)
memory usage: 272.0 bytes
None


,Col_1 Col_2 Col_3 Col_4 Col_5 Col_6 Col_7 Col_8 Col_9 Col_10 Col_11 Col_12 Col_13 Col_14 Col_15
count,50
unique,50
top,0 42 87 15 93 55 24 ...
freq,1


In [1]:
import pandas as pd
data = {
    "Roll_No":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],
    "Name": ["Amit", "Bina", "Chetan", "Dev", "Esha", "Ram", "Gita", "Hari", "Indu", "Jay", "Kiran", "Lata","SHYAM", "Manish", "Neha", "Om"],
    "Age":[5,6,7,8,6,7,8,4,6,7,8,6,7,5,7,None],
    "Marks": [85, 90, 78, 92, 88, 75, 82, 95, 89, 70, 84, 91, 79, 86, 93,None]
}
df = pd.DataFrame(data)
print(df)


    Roll_No    Name  Age  Marks
0         1    Amit  5.0   85.0
1         2    Bina  6.0   90.0
2         3  Chetan  7.0   78.0
3         4     Dev  8.0   92.0
4         5    Esha  6.0   88.0
5         6     Ram  7.0   75.0
6         7    Gita  8.0   82.0
7         8    Hari  4.0   95.0
8         9    Indu  6.0   89.0
9        10     Jay  7.0   70.0
10       11   Kiran  8.0   84.0
11       12    Lata  6.0   91.0
12       13   SHYAM  7.0   79.0
13       14  Manish  5.0   86.0
14       15    Neha  7.0   93.0
15       16      Om  NaN    NaN


In [2]:
import pandas as pd
df=pd.read_csv("employee_dataset_1000.csv")
print(df)
print(df.head(10))
print(df.tail(5))
print(df.info())
print(df.describe())
print(df.columns)
print(df.shape)

    Employee_ID First_Name Last_Name  Gender  Age  Department  \
0       EMP0001      Sneha    Sharma    Male   38   Marketing   
1       EMP0002     Ananya     Singh    Male   47  Operations   
2       EMP0003      Sneha     Joshi    Male   46          IT   
3       EMP0004      Kiran     Patel  Female   46     Finance   
4       EMP0005      Rohan     Joshi  Female   22     Finance   
..          ...        ...       ...     ...  ...         ...   
995     EMP0996      Sneha     Verma    Male   47          HR   
996     EMP0997      Rahul     Kumar  Female   39       Sales   
997     EMP0998      Rahul      Nair    Male   22          HR   
998     EMP0999      Priya     Joshi    Male   55     Finance   
999     EMP1000      Priya      Nair    Male   36          IT   

                Job_Title   Salary  Experience_Years   Hire_Date       City  \
0    Marketing Specialist   716814                15  2023-12-16     Mumbai   
1    Operations Associate  1391139                26  2024-01

In [4]:
import pandas as pd
f=pd.read_csv("employee_dataset_1000.csv")
print(f)

    Employee_ID First_Name Last_Name  Gender  Age  Department  \
0       EMP0001      Sneha    Sharma    Male   38   Marketing   
1       EMP0002     Ananya     Singh    Male   47  Operations   
2       EMP0003      Sneha     Joshi    Male   46          IT   
3       EMP0004      Kiran     Patel  Female   46     Finance   
4       EMP0005      Rohan     Joshi  Female   22     Finance   
..          ...        ...       ...     ...  ...         ...   
995     EMP0996      Sneha     Verma    Male   47          HR   
996     EMP0997      Rahul     Kumar  Female   39       Sales   
997     EMP0998      Rahul      Nair    Male   22          HR   
998     EMP0999      Priya     Joshi    Male   55     Finance   
999     EMP1000      Priya      Nair    Male   36          IT   

                Job_Title   Salary  Experience_Years   Hire_Date       City  \
0    Marketing Specialist   716814                15  2023-12-16     Mumbai   
1    Operations Associate  1391139                26  2024-01